// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "AnglingTool.h"
#include "../Robotmap.h"
#include "../Commands/LiftStatic.h"
#include "../Calc.h"

//absolute limits for the pot on the angle controller
#define ANGLEPOT_MAX 1.2f
#define ANGLEPOT_MIN 0.45f
AnglingTool::AnglingTool() : Subsystem("AnglingTool") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	anglePot = RobotMap::anglingToolAnglePot;
	liftLeadscrew = RobotMap::anglingToolLiftLeadscrew;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void AnglingTool::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new LiftStatic());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void AnglingTool::setSpeed(float speed) {
	liftLeadscrew->Set(speed);
}
float AnglingTool::getAngle() {
	float voltage = anglePot->GetVoltage();
	float target = linearRangeScale(voltage, ANGLEPOT_MIN, ANGLEPOT_MAX, -1.0, 1.0);
	return target;
}
