// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Indexer.h"
#include "../Robotmap.h"
#include "../Commands/IndexIn.h"
Indexer::Indexer() : Subsystem("Indexer") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	indexerWheel = RobotMap::indexerIndexerWheel;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Indexer::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new IndexIn());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
#define REVERSE_MOTOR (-1)
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Indexer::Spin(float speed) {
	setpoint = speed;
	indexerWheel->Set(REVERSE_MOTOR * speed);
}
double Indexer::DebugSpeed() {
	return indexerWheel->GetOutputVoltage();
}
double Indexer::DebugCurrent() {
	return indexerWheel->GetOutputCurrent();
}
double Indexer::DebugSetPoint() {
	return setpoint;
}
