// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Utils/MonoEncoder.h"
#include "../Utils/ThreadlessPID.h"

class ShooterWheel: public Subsystem {
private:
	ThreadlessPID pid;

	CANJaguar* shooterWheel;
	MonoEncoder* encoder;
	
	double target;
public:
	ShooterWheel();
	void InitDefaultCommand();

	void setTargetSpeed(float speed);
	bool atTargetSpeed();
	void runWheelFromOI();
};

class ShooterOther: public Subsystem {
private:
	DigitalInput* loadSensor;
	Servo* kicker;
	Servo* blocker;
public:
	ShooterOther();
	void InitDefaultCommand();
	
	bool holdsDisk();
	void block(bool doit);
	void kick(bool forward);
	bool isLoaded();
};
#endif
